server:
  port: 8081

spring:
  application:
    name: citas-service

  datasource:
    url: jdbc:mysql://localhost:3306/citas_db
    username: root
    password: admin

  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true